### ISSUE TITLE
postgrep's logs showed "ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted"

### ISSUE THREAD

**Issue by dlscodes** [LibrePhotos/librephotos-docker#29]
When the db starts, the following error is displayed: 
`ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted"`

I added the `privileged: true` configuration into the db contianer in docker-compose.yml. Then the db container can work well.
``` yaml
db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${dbUser}
      - POSTGRES_PASSWORD=${dbPass}
      - POSTGRES_DB=${dbName}
    privileged: true  ##### added it here
    volumes:
      - ${dbLocation}:/var/lib/postgresql/data
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
```

I hope the solution can help others. Many thanks for this good project.
