### ISSUE TITLE
Healthcheck on librephotos-frontend?

### ISSUE THREAD

**Issue by joe-eklund** [LibrePhotos/librephotos-docker#89]
Hello-

I am attempting to get a healthcheck for the frontend container of librephotos but have run into an issue. It looks like the frontend image is built on [halverneus/static-file-server](https://github.com/halverneus/static-file-server/blob/master/Dockerfile), which in turn is built on scratch. This means it doesn't have `curl` or `wget`, which is what I typically use for my healthchecks to check http servers.

This means this doesn't work in my compose file:

```
  librephotos-frontend:
    image: reallibrephotos/librephotos-frontend:latest
    container_name: librephotos-frontend
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    depends_on:
      - librephotos-backend
    networks:
      - librephotos_internal
    labels:
      - traefik.enable=false
    healthcheck:
      test: ["CMD", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 15s
```

or something like

```
    healthcheck:
      test: ["CMD", "curl --fail http://localhost:3000 || exit 1"]
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 15s
```

I am wondering if a `HEALTHCHECK` can be added to the Dockerfile, since I don't see anyway to accomplish this using the [docker-compose healthcheck vernacular](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck). [Here is one example on how to accomplish this with scratch based images.](https://github.com/Soluto/golang-docker-healthcheck-example/blob/master/README.md)

Another solution would be to bake in `wget` or `curl` in your image, but unless you had some other reason for it, I understand not wanting it in there.

Thoughts?
